### ISSUE TITLE
Full Support for Kerberos secured Hadoop Cluster

### ISSUE THREAD

**Issue by Jonathanpro** [uber/petastorm#279]
Hello everyone,
Recently I tried to set up petastorm on my company's hadoop cluster.
However as the cluster uses Kerberos for authentication using petastorm failed.
I figured out that petastorm relies on pyarrow which actually supports kerberos authentication.

I hacked  "petastorm/petastorm/hdfs/namenode.py" line 250
and replaced it with
```python
driver = 'libhdfs'
return pyarrow.hdfs.connect("cluserurl", clusterport, user=usernamer, kerb_ticket=ticket_cache_path, driver=driver)
```
This setup actually made it possible to work on a kerberos secured cluster.
For future releases a better support in petastorm for kerberos would be great as the depending pyarrow perfectly works fine with kerberos.

I also used libhdfs instead of libhdfs3 because libhdfs3 doesn't work for me.

Kind regards,
Jonathan

**Comment by selitvin** [comment]
Jonathan, 

Thanks for the suggestion. Let's make get the kerberos authentication supported then.

**Comment by cupdike** [comment]
I'm looking at potentially contributing a patch for this but it's not clear how to best implement it due to the way things bubble up through the function signatures.  It looks like new params kerb_ticket and extra_conf should be available down inside namenode.py.  There is a choice between adding these as optional parameters on top level functions OR instead have the user construct a FileSystemResolver to handle this.  At the moment, some top level methods have FSR-related params (e.g. hdfs_driver) and construct the FSR from them,  and others just take an optional FSR param constructed by the user.  Adding additional optional params is backward compatible but some top level functions already have a lot of params.  Thoughts?

**Comment by selitvin** [comment]
Some thought process behind/history of the current design: 

Originally, the `Reader` class was the high-level object. A user could construct it using a composition of a bunch of other classes: examples of such classes were a worker-pool instance, and filesystem instance. At some stage, this design made our user code base exposed to a lot of details that they did not care about - knowing where to import these objects appeared to be a mental burden we decided to spare.

The idea was to create a higher level, single entrance point that would take only primitive types and by this reduce the interface-area of petastorm - this level of interface is easy to discover since all options are exposed and documented via the docstring of make_reader/make_batch_reader.  

"Advanced" users, still have an option to compose an instance of `Reader` object themselves. 

Following this logic, I agree with your analysis, that we have two choices:
- You can use lower level `Reader` interface and construct it with a FS of choice; or
- Pull up these arguments and expose them via `make_reader`/`make_batch_reader`.

IMO, we are still ok adding a useful options, such as `kerb_ticket` to the `make_reader`/`make_batch_reader` entry points, as they are pretty common and might be more approachable to users than passing already constructed FS instance.

I am open to additional points of view.

**Comment by cupdike** [comment]
I'm seeing an issue in namenode.py where the urlparse parse result sometimes doesn't have a hostname and/or port attribute (Python 3.6).  Assuming six.moves.urllb is just a wrapper for the Python 3 module urllib.parse, there should always be a hostname and port attribute.  Any idea why I would be seeing this?

**Comment by selitvin** [comment]
Nope. That's a great question and very curious to hunt this down. Saw it on someones notebook and waiting to get some clarifications. Was not able to reproduce myself. Has no idea how `ParseResult` instance lost its `hostname` attribute!!! Maybe something weird happens with spark serializing this code as the failure occurs on executor (at least in the case I am aware of).

**Comment by cupdike** [comment]
Yep, it only happens on the executor--which of course makes it harder to sort out.  I did notice that from the driver, it's an instance of:
`<class 'urllib.parse.ParseResult'>`
But on the executor it's:
 `<class 'collections.ParseResult'>`
But since I'm using a virtual environment that is distributed to the executors, I'm not sure what's causing it.

**Comment by selitvin** [comment]
This is very useful. I saw this kind of things happens with pickling of named tuple. One of the base classes of `ParseResult` is a `namedtuple`. I think good chance that if we capture a url string and not `PaarseResult` object the problem would go away.

**Comment by selitvin** [comment]
Here is an initial shot at this: #460. Did not have a chance to test it with a real HDFS - just saw that the tests pass, although, I am not sure how effectively is this piece covered. Please let me know if you get a chance to try it out.

**Comment by cupdike** [comment]
@selitvin So your initial shot did work to solve what was apparently a pickling issue.  But I'm currently stuck trying to get Pyarrow to pick up the kerberos principal when it's running in a YARN container as a Spark executor.  It seems to be ignoring the USER that I pass in and any jaas conf I try to use.  Any idea how the principal is supposed to be supplied?  

```
debug is  true storeKey false useTicketCache true useKeyTab false doNotPrompt true ticketCache is null isInitiator true KeyTab is null refreshKrb5Config is false principal is null tryFirstPass is false useFirstPass is false storePass is false clearPass is false
Acquire TGT from Cache
Principal is null
null credentials from Ticket Cache
        [Krb5LoginModule] authentication failed 
Unable to obtain Principal Name for authentication 
        [UnixLoginModule]: added UnixPrincipal,
                UnixNumericUserPrincipal,
                UnixNumericGroupPrincipal(s),
             to Subject
Debug is  true storeKey false useTicketCache true useKeyTab false doNotPrompt true ticketCache is <snip>/kerbTic isInitiator true KeyTab is null refreshKrb5Config is false principal is null tryFirstPass is false useFirstPass is false storePass is false clearPass is false
Acquire TGT from Cache
Principal is null
null credentials from Ticket Cache
        [Krb5LoginModule] authentication failed 
Unable to obtain Principal Name for authentication 
hdfsBuilderConnect(forceNewInstance=1, nn=whatsinaname, port=42000, kerbTicketCachePath=<snip>/kerbTic, userName=myuser@MYREALM) error:
LoginException: Unable to obtain Principal Name for authentication org.apache.hadoop.security.KerberosAuthException: failure to login: for user: myuser@MYREALMusing ticket cache file: <snip>/kerbTic javax.security.auth.login.LoginException: Unable to obtain Principal Name for authentication 
    at org.apache.hadoop.security.UserGroupInformation.getUGIFromTicketCache(UserGroupInformation.java:811)
    at org.apache.hadoop.security.UserGroupInformation.getBestUGI(UserGroupInformation.java:746)
    at org.apache.hadoop.fs.FileSystem.newInstance(FileSystem.java:404)
Caused by: javax.security.auth.login.LoginException: Unable to obtain Principal Name for authentication 
    at com.sun.security.auth.module.Krb5LoginModule.promptForName(Krb5LoginModule.java:841)
    at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:704)
    at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
    at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
    at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
    at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
    at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
    at org.apache.hadoop.security.UserGroupInformation.getUGIFromTicketCache(UserGroupInformation.java:792)
    ... 2 more
Traceback (most recent call last):
  File "app.py", line 219, in <module>
    generate_petastorm_dataset(inputFileRecs)
  File "app.py", line 204, in generate_petastorm_dataset
    resolver=FilesystemResolver(output_url, spark.sparkContext._jsc.hadoopConfiguration(), user=USER, hdfs_driver=DRIVER, kerb_ticket=kerbTicAbsPath, extra_conf={})
  File "<snip>/environment/lib/python3.6/site-packages/petastorm-0.8.0-py3.6.egg/petastorm/fs_utils.py", line 114, in __init__
    kerb_ticket=kerb_ticket, extra_conf=extra_conf)
  File "<snip>/environment/lib/python3.6/site-packages/petastorm-0.8.0-py3.6.egg/petastorm/hdfs/namenode.py", line 273, in hdfs_connect_namenode
    kerb_ticket=kerb_ticket, extra_conf=extra_conf)
  File "<snip>/environment/lib/python3.6/site-packages/pyarrow/hdfs.py", line 215, in connect
    extra_conf=extra_conf)
  File "<snip>/environment/lib/python3.6/site-packages/pyarrow/hdfs.py", line 40, in __init__
    self._connect(host, port, user, kerb_ticket, driver, extra_conf)
  File "pyarrow/io-hdfs.pxi", line 105, in pyarrow.lib.HadoopFileSystem._connect
  File "pyarrow/error.pxi", line 80, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: HDFS connection failed
```

**Comment by selitvin** [comment]
Unfortunately I do not know. Is this more of an pyarrow issue or you think this is a problem with Petastorm code? Unfortunately I do not have access to a Kerberos secured hadoop cluster so it's hard for me to debug this issue.

**Comment by cupdike** [comment]
I was able to get past this error.  Seems like it was actually caused by the file supplied to the kerbTicketCachePath not actually being at the specified location.  I was using the --files option with spark-submit when it should have been --py-files.
