### ISSUE TITLE
AssertionError with parquet data

### ISSUE THREAD

**Issue by bluesummers1129** [uber/petastorm#346]
I am currently using Petastorm + Horovod + Tensorflow to prototype a wide network. I have parquet data organized across multiple files with the following schema:
```
one_hot_index_1 | one_hot_index_2 | multi_hot_index_1
1 | 4 | "3,4,5"
0 | 10 | "1,2"
```
When I try to run a Horovod based Spark training job against the dataset produced by make_batch_reader and make_petastorm_dataset, I get the following error:
```
[1,2]<stderr>:WARNING:tensorflow:Your dataset iterator ran out of data; interrupting training. Make sure that your dataset can generate at least `steps_per_epoch * epochs` batches (in this case, 28470 batches). You may need touse the repeat() function when building your dataset.
[1,3]<stderr>:    aggregator.finalize()
[1,3]<stderr>:  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_utils.py", line 108, in finalize
[1,3]<stderr>:    self.results[0] /= self.num_samples_or_steps
[1,3]<stderr>:IndexError: list index out of range
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
[1,2]<stderr>:    "__main__", fname, loader, pkg_name)
[1,2]<stderr>:  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
[1,2]<stderr>:    exec code in run_globals
[1,2]<stderr>:  File "/usr/local/lib64/python2.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 55, in <module>
[1,2]<stderr>:    main(codec.loads_base64(sys.argv[1]))
[1,2]<stderr>:  File "/usr/local/lib64/python2.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 47, in main
[1,2]<stderr>:    result = fn(*args, **kwargs)
[1,2]<stderr>:  File "/mnt/Optimitron/optimitron_spark_tf.py", line 325, in input_fn_keras
[1,2]<stderr>:  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.py", line 880, in fit
[1,2]<stderr>:    validation_steps=validation_steps)
[1,2]<stderr>:  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 346, in model_iteration
[1,2]<stderr>:    aggregator.finalize()
[1,2]<stderr>:  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_utils.py", line 108, in finalize
[1,2]<stderr>:    self.results[0] /= self.num_samples_or_steps
[1,2]<stderr>:IndexError: list index out of range
[1,0]<stderr>:2019-04-05 13:20:04.443204: W tensorflow/core/framework/op_kernel.cc:1389] Unknown: exceptions.AssertionError:
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:
[1,0]<stderr>:  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
[1,0]<stderr>:    ret = func(*args)
[1,0]<stderr>:
[1,0]<stderr>:  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 449, in generator_py_func
[1,0]<stderr>:    values = next(generator_state.get_iterator(iterator_id))
[1,0]<stderr>:
[1,0]<stderr>:  File "/usr/local/lib/python2.7/site-packages/petastorm/tf_utils.py", line 377, in dequeue_sample_impl
[1,0]<stderr>:    for row in reader:
[1,0]<stderr>:
[1,0]<stderr>:  File "/usr/local/lib/python2.7/site-packages/petastorm/reader.py", line 628, in next
[1,0]<stderr>:    return self.__next__()
[1,0]<stderr>:
[1,0]<stderr>:  File "/usr/local/lib/python2.7/site-packages/petastorm/reader.py", line 622, in __next__
[1,0]<stderr>:    return self._results_queue_reader.read_next(self._workers_pool, self.schema, self.ngram)
[1,0]<stderr>:
[1,0]<stderr>:  File "/usr/local/lib/python2.7/site-packages/petastorm/arrow_reader_worker.py", line 50, in read_next
[1,0]<stderr>:    assert len(column.data.chunks) == 1
[1,0]<stderr>:
[1,0]<stderr>:AssertionError
```
I don't need to use repeat() given that I have num_epochs=None for make_batch_reader.

Curiously, I get a similar error when running on a single local machine using a plain old Tensorflow session as well:
```
Exception tensorflow.python.framework.errors_impl.CancelledError: CancelledError() in <bound method _Callable.__del__ of <tensorflow.python.client.session._Callable object at 0x1c999af10>> ignored
Exception tensorflow.python.framework.errors_impl.CancelledError: CancelledError() in <bound method _Callable.__del__ of <tensorflow.python.client.session._Callable object at 0x1c99a6690>> ignored
Exception tensorflow.python.framework.errors_impl.CancelledError: CancelledError() in <bound method _Callable.__del__ of <tensorflow.python.client.session._Callable object at 0x199c60f10>> ignored
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-41-1a93d45a2c0a> in <module>()
     79                     steps_per_epoch=int(num_train_rows / BATCH_SIZE),
     80                     validation_steps=int(num_valid_rows / BATCH_SIZE),
---> 81                     epochs=training_epochs)

/Users/yggan/anaconda/envs/py34/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.pyc in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, max_queue_size, workers, use_multiprocessing, **kwargs)
    878           initial_epoch=initial_epoch,
    879           steps_per_epoch=steps_per_epoch,
--> 880           validation_steps=validation_steps)
    881 
    882   def evaluate(self,

/Users/yggan/anaconda/envs/py34/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_arrays.pyc in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, mode, validation_in_fit, **kwargs)
    264           # `ins` can be callable in DistributionStrategy + eager case.
    265           actual_inputs = ins() if callable(ins) else ins
--> 266           batch_outs = f(actual_inputs)
    267         except errors.OutOfRangeError:
    268           logging.warning('Your dataset iterator ran out of data; '

/Users/yggan/anaconda/envs/py34/lib/python2.7/site-packages/tensorflow/python/keras/backend.pyc in __call__(self, inputs)
   3074 
   3075     fetched = self._callable_fn(*array_vals,
-> 3076                                 run_metadata=self.run_metadata)
   3077     self._call_fetch_callbacks(fetched[-len(self._fetches):])
   3078     return nest.pack_sequence_as(self._outputs_structure,

/Users/yggan/anaconda/envs/py34/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in __call__(self, *args, **kwargs)
   1437           ret = tf_session.TF_SessionRunCallable(
   1438               self._session._session, self._handle, args, status,
-> 1439               run_metadata_ptr)
   1440         if run_metadata:
   1441           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/Users/yggan/anaconda/envs/py34/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.pyc in __exit__(self, type_arg, value_arg, traceback_arg)
    526             None, None,
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
    529     # Delete the underlying status object from memory otherwise it stays alive
    530     # as there is a reference to status from this from the traceback due to

UnknownError: exceptions.AssertionError: 
Traceback (most recent call last):

  File "/Users/yggan/anaconda/envs/py34/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/Users/yggan/anaconda/envs/py34/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 449, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/Users/yggan/anaconda/envs/py34/lib/python2.7/site-packages/petastorm/tf_utils.py", line 390, in dequeue_sample_impl
    for row in reader:

  File "/Users/yggan/anaconda/envs/py34/lib/python2.7/site-packages/petastorm/reader.py", line 628, in next
    return self.__next__()

  File "/Users/yggan/anaconda/envs/py34/lib/python2.7/site-packages/petastorm/reader.py", line 622, in __next__
    return self._results_queue_reader.read_next(self._workers_pool, self.schema, self.ngram)

  File "/Users/yggan/anaconda/envs/py34/lib/python2.7/site-packages/petastorm/arrow_reader_worker.py", line 50, in read_next
    assert len(column.data.chunks) == 1

AssertionError


	 [[{{node PyFunc}}]]
	 [[{{node IteratorGetNext_425}}]]
```
But, this error goes away if I explicitly reduce the number of parquet files on the path.

Is there some limitation on how the parquet files should be partitioned?

**Comment by selitvin** [comment]
This is a wrong assumption in the petastorm code. Here is a PR that I think should fix the issue for you: #347 . Can you please try?

**Comment by bluesummers1129** [comment]
I'll try and report back, thanks!

**Comment by bluesummers1129** [comment]
I'm now getting past that issue, but I'm still running into some problems that are probably related to how I'm batching:
```
[1,1]<stderr>:WARNING:tensorflow:Your dataset iterator ran out of data; interrupting training. Make sure that your dataset can generate at least `steps_per_epoch * epochs` batches (in this case, 100 batches). You may need touse the repeat() function when building your dataset.
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
[1,1]<stderr>:    "__main__", fname, loader, pkg_name)
[1,1]<stderr>:  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
[1,1]<stderr>:    exec code in run_globals
[1,1]<stderr>:  File "/usr/local/lib64/python2.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 55, in <module>
[1,1]<stderr>:    main(codec.loads_base64(sys.argv[1]))
[1,1]<stderr>:  File "/usr/local/lib64/python2.7/site-packages/horovod/spark/task/mpirun_exec_fn.py", line 47, in main
[1,1]<stderr>:    result = fn(*args, **kwargs)
[1,1]<stderr>:  File "/mnt/Optimitron/optimitron_spark_tf.py", line 318, in input_fn_keras
[1,1]<stderr>:  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.py", line 880, in fit
[1,1]<stderr>:    validation_steps=validation_steps)
[1,1]<stderr>:  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 346, in model_iteration
[1,1]<stderr>:    aggregator.finalize()
[1,1]<stderr>:  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_utils.py", line 108, in finalize
[1,1]<stderr>:    self.results[0] /= self.num_samples_or_steps
[1,1]<stderr>:IndexError: list index out of range
```

This is strange because I'm reading in parquet training data that has exactly 40,000 records and validation data that has exactly 4,000 records, and I'm setting the Keras model training in a manner that I think should leave me with the right batching:
```
    # I have hvd.size() giving 4
    train_rows = 40000
    val_rows = 4000
    batch_size = 100
    # Make Petastorm readers.
    with make_batch_reader(training_path, num_epochs=None,
                           cur_shard=hvd.rank(), shard_count=hvd.size(), schema_fields=[f for f in one_hot_indexes.keys()] + [f for f in multi_hot_indexes.keys()] + ['label'],
                           hdfs_driver=PETASTORM_HDFS_DRIVER) as train_reader:
        with make_batch_reader(valid_path, num_epochs=None,
                               cur_shard=hvd.rank(), shard_count=hvd.size(), schema_fields=[f for f in one_hot_indexes.keys()] + [f for f in multi_hot_indexes.keys()] + ['label'],
                               hdfs_driver=PETASTORM_HDFS_DRIVER) as val_reader:
            # Convert readers to tf.data.Dataset.
            train_ds = make_petastorm_dataset(train_reader) \
                .apply(tf.data.experimental.unbatch()) \
                .shuffle(int(train_rows / hvd.size())) \
                .batch(batch_size) \
                .map(lambda x: (create_input(x), x.label))

            val_ds = make_petastorm_dataset(val_reader) \
                .apply(tf.data.experimental.unbatch()) \
                .batch(batch_size) \
                .map(lambda x: (create_input(x), x.label))

            history = model.fit(
                train_ds,
                validation_data=val_ds,
                steps_per_epoch=int(train_rows / batch_size / hvd.size()),
                validation_steps=int(val_rows / batch_size / hvd.size()),
                callbacks=callbacks,
                verbose=verbose,
                epochs=1
            )
```
I confess I'm fairly new to Horovod + Tensorflow + Petastorm, so I'm not sure if these steps_per_epoch and validation_steps make sense or if this is still a Petastorm issue?

**Comment by selitvin** [comment]
Is it possible that you have less than 4 row-groups in your dataset? The sharding is done at the row-group granularity. In this case, one of your workers would not produce any rows.

Some thoughts:
- Remove sharding and maybe increasing your shuffling size. 
- Reducing 'parquet.block.size' when the dataset is generated.
- Increase number of parquet files (as that would automatically increase number of rowgroups)
- Use larger dataset. It will have more row-groups.

Anyway, I will create a PR that would raise an explicit error in this case as I think the user should be alerted in this case.

**Comment by selitvin** [comment]
You can try PR #348  which will alert of this kind of issues.
