### ISSUE TITLE
make_batch_reader fails on nested struct

### ISSUE THREAD

**Issue by htokgoz1** [uber/petastorm#353]
I have an external parquet file that I'm trying to load using the hello world example, but it fails as such:
```Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 389, in infer_or_load_unischema
    return get_schema(dataset)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 343, in get_schema
    'Could not find _common_metadata file. Use materialize_dataset(..) in'
petastorm.etl.dataset_metadata.PetastormMetadataError: Could not find _common_metadata file. Use materialize_dataset(..) in petastorm.etl.dataset_metadata.py to generate this file in your ETL code. You can generate it on an existing dataset using petastorm-generate-metadata.py

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "petastorm_genome.py", line 30, in <module>
    python_hello_world()
  File "petastorm_genome.py", line 22, in python_hello_world
    with make_batch_reader(dataset_url, schema_fields=FIELDS) as reader:
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/petastorm/reader.py", line 349, in make_batch_reader
    transform_spec=transform_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/petastorm/reader.py", line 432, in __init__
    stored_schema = infer_or_load_unischema(self.dataset)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/petastorm/etl/dataset_metadata.py", line 393, in infer_or_load_unischema
    return Unischema.from_arrow_schema(dataset)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/petastorm/unischema.py", line 266, in from_arrow_schema
    codec, np_type = _numpy_and_codec_from_arrow_type(field_type)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/petastorm/unischema.py", line 392, in _numpy_and_codec_from_arrow_type
    raise ValueError('Cannot auto-create unischema due to unsupported column type {}'.format(field_type))
ValueError: Cannot auto-create unischema due to unsupported column type struct<featureId: int32, featureValue: int32, featureValueVersions: struct<key_value: list<key_value: struct<key: int32, value: int32> not null>>, _featureNameSpace: int16>```

**Comment by htokgoz1** [comment]
If there are unsupported types, could you please make this clear in the documentation? Also, is it possible to have make_batch_reader support the `warn_only` parameter so that we can skip features that aren't supported? The schema passed into make_batch_reader allows us to skip top level column names, but if we have nested fields, can we make it ignore the unsupported subfield and deserialize the rest of the struct? Is there a time frame for supporting list structures?

**Comment by selitvin** [comment]
The field in your error message (`struct<featureId: int32, featureValue: int32, featureValueVersions: struct<key_value: list<key_value: struct<key: int32, value: int32> not null>>, _featureNameSpace: int16>` is not supported by pyarrow (ARROW-1644) as an aggregate field that is not a list. We are watching that arrow ticket and once it is resolved, will reenable it in petastorm as well. 

PR #357 makes sure the field is ignored with a warning and does not cause the crash.  

Would appreciate if you could let me know if that PR solves your issue.
