### ISSUE TITLE
Generating meta data for existing datasets

### ISSUE THREAD

**Issue by w1nk** [uber/petastorm#380]
Hello!

  I've got an existing dataset of parquet files sitting in HDFS.  I'm trying to load them via petastorm, but I'm receiving errors that the meta data can't be located:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/petastorm/etl/dataset_metadata.py", line 391, in infer_or_load_unischema
    return get_schema(dataset)
  File "/opt/conda/lib/python3.6/site-packages/petastorm/etl/dataset_metadata.py", line 345, in get_schema
    'Could not find _common_metadata file. Use materialize_dataset(..) in'
petastorm.etl.dataset_metadata.PetastormMetadataError: Could not find _common_metadata file. Use materialize_dataset(..) in petastorm.etl.dataset_metadata.py to generate this file in your ETL code. You can generate it on an existing dataset using petastorm-generate-metadata.py

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    pytorch_word2vec(dataset_url="hdfs://path_to/parquets")
  File "test.py", line 8, in pytorch_word2vec
    with DataLoader(make_batch_reader(dataset_url)) as train_loader:
  File "/opt/conda/lib/python3.6/site-packages/petastorm/reader.py", line 350, in make_batch_reader
    transform_spec=transform_spec)
  File "/opt/conda/lib/python3.6/site-packages/petastorm/reader.py", line 420, in __init__
    stored_schema = infer_or_load_unischema(self.dataset)
  File "/opt/conda/lib/python3.6/site-packages/petastorm/etl/dataset_metadata.py", line 395, in infer_or_load_unischema
    return Unischema.from_arrow_schema(dataset)
  File "/opt/conda/lib/python3.6/site-packages/petastorm/unischema.py", line 251, in from_arrow_schema
    meta = parquet_dataset.pieces[0].get_metadata(parquet_dataset.fs.open)
IndexError: list index out of range
```

This makes a bit of sense, as I don't have any petastorm specific metadata at the moment.  I took the advice of the error and tried to run petastorm-generate-metadata.py , however when I do that, I receive the same error:

```
Traceback (most recent call last):
  File "/opt/conda/bin/petastorm-generate-metadata.py", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/petastorm/etl/petastorm_generate_metadata.py", line 155, in main
    _main(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/petastorm/etl/petastorm_generate_metadata.py", line 148, in _main
    hdfs_driver=args.hdfs_driver)
  File "/opt/conda/lib/python3.6/site-packages/petastorm/etl/petastorm_generate_metadata.py", line 77, in generate_petastorm_metadata
    schema = get_schema(dataset)
  File "/opt/conda/lib/python3.6/site-packages/petastorm/etl/dataset_metadata.py", line 345, in get_schema
    'Could not find _common_metadata file. Use materialize_dataset(..) in'
petastorm.etl.dataset_metadata.PetastormMetadataError: Could not find _common_metadata file. Use materialize_dataset(..) in petastorm.etl.dataset_metadata.py to generate this file in your ETL code. You can generate it on an existing dataset using petastorm-generate-metadata.py
```

Is there anyway to create the metadata without regenerating my parquet dataset through the petastorm interface?

**Comment by selitvin** [comment]
Please try using `make_batch_reader` to read from stores that were not generated using petastorm.
