### ISSUE TITLE
Unischema variable shape error

### ISSUE THREAD

**Issue by berendjansen** [uber/petastorm#633]
Hi, 

I'm trying to use the spark dataset converter to build a tensorflow dataset. I am training an LSTM on sequences with variable length. 

In the transform spec function I pass to `make_tf_dataset`, I set `shape=(None, 34)` for the UnischemaField:
```
transform_spec_fn = TransformSpec(
  transform_row, 
  edit_fields=[('numpy_sequence', np.float32, shape=(None, 34), True)], 
  selected_fields=['numpy_sequence']
)
```

This is to indicate that sequences can be of variable length, which corresponds to the documentation of `UnischemaField`:

```
shape: shape of the multidimensional array. None value is used to define a dimension with variable number of
elements. E.g. ``(None, 3)`` defines a point cloud with three coordinates but unknown number of points.
```

However, when I'm trying to build the dataset, I get an error saying that my field does not have the shape `(None, 34)`. 
```
with converter_train.make_tf_dataset(transform_spec=transform_spec_fn,) as train_dataset:
    ...
```

Results in:
```
Traceback (most recent call last):
  File "/databricks/python/lib/python3.7/site-packages/petastorm/workers_pool/thread_pool.py", line 62, in run
    self._worker_impl.process(*args, **kargs)
  File "/databricks/python/lib/python3.7/site-packages/petastorm/arrow_reader_worker.py", line 167, in process
    lambda: self._load_rows(parquet_file, piece, shuffle_row_drop_partition))
  File "/databricks/python/lib/python3.7/site-packages/petastorm/cache.py", line 39, in get
    return fill_cache_func()
  File "/databricks/python/lib/python3.7/site-packages/petastorm/arrow_reader_worker.py", line 167, in <lambda>
    lambda: self._load_rows(parquet_file, piece, shuffle_row_drop_partition))
  File "/databricks/python/lib/python3.7/site-packages/petastorm/arrow_reader_worker.py", line 219, in _load_rows
    .map(lambda x, f=field: self._check_shape_and_ravel(x, f))
  File "/databricks/python/lib/python3.7/site-packages/pandas/core/series.py", line 3630, in map
    new_values = super()._map_values(arg, na_action=na_action)
  File "/databricks/python/lib/python3.7/site-packages/pandas/core/base.py", line 1154, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/lib.pyx", line 2327, in pandas._libs.lib.map_infer
  File "/databricks/python/lib/python3.7/site-packages/petastorm/arrow_reader_worker.py", line 219, in <lambda>
    .map(lambda x, f=field: self._check_shape_and_ravel(x, f))
  File "/databricks/python/lib/python3.7/site-packages/petastorm/arrow_reader_worker.py", line 178, in _check_shape_and_ravel
    .format(name=field.name, shape=field.shape))
ValueError: field numpy_sequence must be the shape (None, 34)
```

Looking at the code in `_check_shape_and_ravel`, it seems like using `shape=(None, 34)` will always throw an error instead of allowing variable sizes. 

If I filter my dataset to have a sequences of a fixed length 10, and I pass `shape=(10, 34)`, it does work (which is not surprising).

I went through all the source code but I can't find what's causing the problem. Maybe the problem could be resolved by using `_load_rows_with_predicates` instead of `_load_rows` in `ArrowReaderWorker`, as it doesn't call `_check_shape_and_ravel`?

Am I missing something here?

**Comment by selitvin** [comment]
A variable dimension is not supported in this case. If a dimension is variable, we are not able to properly coalesce multiple records into a batch result (would need to support ragged arrays for that). Created #634 to raise an explicit error in this case, since, you are right, the current exception is unclear.

**Comment by berendjansen** [comment]
Thanks for the quick reply, much appreciated. 

Is there any smart workaround to prevent this error?

I could pad my sequences in the spark dataframe and mask later? This would mean that every sequence would get the maximum length found in the dataset.

**Comment by selitvin** [comment]
I think padding is a reasonable option.
