### ISSUE TITLE
OSError: Passed non-file path when passing an s3 path to materialize_dateset

### ISSUE THREAD

**Issue by Jomonsugi** [uber/petastorm#645]
This issue could be related to this [one](https://github.com/uber/petastorm/issues/285), however I am attempting to use `materialize_dataset` with an s3 path, not hdfs. 

Given `output_url='s3://my-bucket/petastorm/test'` the following error occurs:

```
An error was encountered:
Passed non-file path: my-bucket/petastorm/test
Traceback (most recent call last):
  File "/usr/lib/environs/e-a-2019.03-py-3.7.3/lib/python3.7/site-packages/pyarrow/parquet.py", line 1182, in __init__
    open_file_func=partial(_open_dataset_file, self._metadata)
  File "/usr/lib/environs/e-a-2019.03-py-3.7.3/lib/python3.7/site-packages/pyarrow/parquet.py", line 1377, in _make_manifest
    .format(path))
OSError: Passed non-file path: my-bucket/petastorm/test
```

Although I can see that the error is traced to  [_make_manifest](https://github.com/apache/arrow/blob/master/python/pyarrow/parquet.py#L1410), seemingly when  `ParquetDataset` is initiated [here](https://github.com/uber/petastorm/blob/7377bb7781aa82b80631aeeabbd77f50de45f458/petastorm/etl/dataset_metadata.py#L107), I haven't been able to figure out the root cause. 

Strangely, while I was scoping the use of petastorm with multiple iterations of using `materialize_dataset` over the past couple weeks, it worked without a hitch, then this error popped up seemingly out of the blue. I found some empathy [here](https://github.com/dask/s3fs/issues/253), but thus far nothing to shake the error.

**Comment by Jomonsugi** [comment]
I was able to solve this problem by writing a spark dataframe out in parquet format outside of `materialize_dataset` and then running the `materialize_dataset` with nothing but a print statement so that the `_common_metadata` file is added. 

```
def add_petastorm_metadata():
        
        with materialize_dataset(spark, 
                                 output_url, 
                                 schema, 
                                 row_group_size_mb):
            
            print('_common_metadata file added')

add_petastorm_metadata()
```
