### ISSUE TITLE
make_batch_reader called by make_torch_loader "got an unexpected keyword argument 'shard_seed'"

### ISSUE THREAD

**Issue by quocdat32461997** [uber/petastorm#742]
I was trying to use HorovodRunner (a wrapper of Horovod to run on Databricks) + Petastorm for distributed training. 

Briefly, I used `spark` and `make_spark_converter` to read parquet files and convert into converter. Then, it was consumed by `make_torch_dataloader` with `shuffle_row_groups=True, shuffling_queue_capacity=256, shard_seed=0`. However, it raised the error, `TypeError: make_batch_reader() got an unexpected keyword argument 'shard_seed'
`. These steps are within a function, say `main`, which is then executed by running `HorovodRunner.run(main)`. 

Dependencies:
* Azure ML configs: Driver: Standard_L32s, Workers: Standard_L32s, 4-16 workers, 7.3 LTS ML (includes Apache Spark 3.0.1, Scala 2.12)
 
Trackback here:
```
[1,31]<stderr>:TypeError: make_batch_reader() got an unexpected keyword argument 'shard_seed'
[1,75]<stderr>:Traceback (most recent call last):
[1,75]<stderr>:  File "<string>", line 1, in <module>
[1,75]<stderr>:  File "/databricks/.python_edge_libs/sparkdl/horovod/runner.py", line 222, in wrapped_main
[1,75]<stderr>:    return_value = main(**kwargs)
[1,75]<stderr>:  File "<command-2705527668713177>", line 70, in distributed_training
[1,75]<stderr>:  File "/databricks/python/lib/python3.7/site-packages/petastorm/spark/spark_dataset_converter.py", line 394, in __enter__
[1,75]<stderr>:    self.reader = make_batch_reader(self.parquet_file_url_list, **self.petastorm_reader_kwargs)
[1,75]<stderr>:TypeError: make_batch_reader() got an unexpected keyword argument 'shard_seed'
```

**Comment by selitvin** [comment]
Interesting. Can you please take a look at https://github.com/uber/petastorm/pull/745/files . I tried to reproduce the failure by modifying one of petastorm examples. I was able to successfully run this modified example. Is it different from what you are trying to do? If yes, can you please provide for me a way to reproduce this failure? Perhaps a small code snippet?

**Comment by quocdat32461997** [comment]
Hi, sorry for taking too long. Probably, due to version mismatch. I'm going to close this.
